Step1
code-squad/java-bowling pull request #46
Opened 2018-01-23 09:13 UTC by retrokarr

구현이 힘드네요 ㅠㅠ
어딘가 마음에 안드는 것들이 많지만, 일단 구현이 완료되어 PR날려 봅니다.
람다, 스트림, 옵셔널이 모두 생소해서 이쪽 부분에 대해서 많은 조언 부탁드립니다.

2018-01-23 11:26 UTC, javajigi requested changes
전체적인 구조도 깔끔하고, 테스트도 꼼꼼하게 잘 하셨네요. 약간의 구조 변경에 대한 피드백 남겨봅니다.

2018-01-23 11:26 UTC, javajigi commented on src/main/java/bowling/domain/BowlingGame.java
> +        if(players == null)
players.isEmpty()도 같이 테스트하는 것이 좋을 것 같아요.

2018-01-23 11:26 UTC, javajigi commented on src/main/java/bowling/domain/Frame.java
> +
status()를 반환하는 방식 보다 isStrike(), isSpare(), isMiss()와 같은 메소드를 추가해 활용하는 것은 어떨까요? 물론 내부적으로는 FrameStatus를 사용하겠죠.

2018-01-23 11:26 UTC, javajigi commented on src/main/java/bowling/domain/Frame.java
> +    protected Pin secondTry;
Pin 객체 추가 👍

2018-01-23 11:26 UTC, javajigi commented on src/main/java/bowling/enums/FrameStatus.java
> +    public static FrameStatus getStatus(Pin firstTry, Pin secondTry) {
Pin을 사용해 처리하면 되지 않을까요?

```
if (firstTry.isStrike()) {
  return STRIKE;
}

if (firstTry.isSpare(secondTry)) {
  return SPARE;
}
...
```

2018-01-23 11:26 UTC, javajigi commented on src/main/java/bowling/enums/FrameStatus.java
> +    }
다음과 같이 구현해도 되요.

```
public boolean isEnd() {
  return this == STRIKE || this == SPARE || this == MISS;
}
```

2018-01-23 11:26 UTC, javajigi commented on src/main/java/bowling/domain/BowlingGame.java
> +        this.playerQueue = new PlayerQueue(players);
Players가 사용자 목록을 가지는 구조인데요.
Players가 PlayerQueue를 가지는 구조로 구현할 수는 없을까요?
제가 PlayerQueue를 정확히 파악하지 못해 드리는 의견인데요. 가능하지도 않을까라는 생각이 들어서요.

2018-01-23 11:26 UTC, javajigi commented on src/main/java/bowling/Main.java
> +            OutputView.showScoreBoard(bowlingGame.getPlayers());
비지니스 로직을 구현하고 있는 Players를 직접 노출하기 보다는 DTO를 통해 결과 데이터를 반환하면 어떨까요? 
다음과 같은 구조가 된다면 굳이 Players을 노출하지 않아도 될 것 같은데요.

```
Board board = bowlingGame.createBoard();
```

2018-01-23 14:11 UTC, retrokarr commented on src/main/java/bowling/domain/BowlingGame.java
> +        if(players == null)
넵 추가하도록 하겠습니다.

2018-01-23 14:11 UTC, retrokarr commented on src/main/java/bowling/domain/Frame.java
> +    protected Pin secondTry;
:)

2018-01-23 14:17 UTC, retrokarr commented on src/main/java/bowling/enums/FrameStatus.java
> +    }
앗 ㅋㅋㅋ 변경하겠습니다.

2018-01-23 14:17 UTC, retrokarr commented on src/main/java/bowling/enums/FrameStatus.java
> +    public static FrameStatus getStatus(Pin firstTry, Pin secondTry) {
음 넵 그쪽이 훨씬 깔끔할 것 같습니다. 구현을 이 코드부터 시작했는데, 리팩토링할 부분을 놓치고 있었네요.

2018-01-23 14:36 UTC, retrokarr commented on src/main/java/bowling/domain/BowlingGame.java
> +        this.playerQueue = new PlayerQueue(players);
Players list와 queue를 둔 이유를 각각 설명드리자면, queue의 경우에는 현재 공을 굴려야 할 플레이어에 쉽게 접근하기 위해서 만들었구요(스텝1은 한명의 유저만 받지만, 미리 구현하는게 좋을듯 싶어서 이렇게 진행해 봤습니다.), list는 순전히 view를 그릴 때 입력한 순서대로 출력하기 위해서 만들었습니다.
Players 내에 list대신에 queue로 교체해도 게임 플레이에는 무관하지만, view를 그릴때는 순서에 변화가 생기게 됩니다. 현재 플레이어는 항상 제일 위쪽에 위치하게 될거구요.

Players내에 list대신 queue로 대신할 방법은 존재합니다. 최초에 플레이어 리스트를 받아서, 이를 알파뱃 순으로 정렬 하고 queue에 순서대로 넣은 후, 게임을 진행합니다.
대신 출력을 할때는 player를 알파뱃 순으로 정렬 후에 출력하면 될 것 같습니다.

2018-01-23 14:50 UTC, retrokarr commented on src/main/java/bowling/domain/Frame.java
> +
어느 순간 옛날 스타일로 다시 돌아가네요. 변경하겠습니다.

2018-01-23 14:56 UTC, retrokarr commented on src/main/java/bowling/Main.java
> +            OutputView.showScoreBoard(bowlingGame.getPlayers());
넵 그편이 더 좋을것 같습니다.

2018-01-24 00:27 UTC, retrokarr commented on src/main/java/bowling/domain/BowlingGame.java
> +        if(players == null)
가장 끝단인 Players와 PlayerQueue에서 유효성 체크가 있어서 해당 함수가 중복이라 생각하여 삭제했습니다.

2018-01-24 11:44 UTC, retrokarr commented on src/main/java/bowling/domain/BowlingGame.java
> +        this.playerQueue = new PlayerQueue(players);
구현을 하다보니까 List를 사용해서도 변수 추가없이 간단하게 현재 플레이어를 구할수 있어서 Queue를 삭제했습니다.

2018-01-24 21:36 UTC, merged