Step 1 : Basic Bowling Game Board
code-squad/java-bowling pull request #50
Opened 2018-01-23 14:41 UTC by trytocloud

2018-01-24 00:54 UTC, javajigi requested changes
Optional과 Stream 학습 후에 바로 적용했네. 특히 Optional을 적극적으로 활용한 모습이 인상적이네. 코드는 전체적으로 깔끔하다. 미션의 난이도가 있었을텐데 👍 . 피드백 중에 다형성을 연습할 수 있는 좋은 곳이 있으니까 한번 고민해 봐라.

2018-01-24 00:54 UTC, javajigi commented on src/main/java/bowling/domain/Frame.java
> +        return message;
이 메소드에 if문이 많은데 이 if문을 제거할 수 있는 좋은 방법 없을까?
다형성 개념을 이용해서 제거할 수 있는 방법을 한번 찾아보면 어떨까?

2018-01-24 00:54 UTC, javajigi commented on src/main/java/bowling/domain/LastFrame.java
> +public class LastFrame extends Frame {
만약 상속 관계가 아니라 조합 관계로 구현 가능할까?
조합이라면 Frame을 생성자의 인자로 받는 구조로 구현한다면...

2018-01-24 00:54 UTC, javajigi commented on src/test/java/bowling/domain/FrameDefaultTest.java
> +public abstract class FrameDefaultTest {
이 클래스가 굳이 추상 클래스일 필요가 있나?

2018-01-25 13:20 UTC, trytocloud commented on src/main/java/bowling/domain/LastFrame.java
> +public class LastFrame extends Frame {
조합 관계로 구현하니까 둘 간의 애매하던 부분이 더 잘 정리되는 것 같아요.

2018-01-25 13:20 UTC, trytocloud commented on src/test/java/bowling/domain/FrameDefaultTest.java
> +public abstract class FrameDefaultTest {
이 Test가 수행되지 않고 상속받은 Test에서 수행되게 하려고 abstract로 했어요.
실제로 사용되는 객체를 생성하는 부분도 이 클래스는 안 가지고 있는 형태에요.

2018-01-25 13:22 UTC, trytocloud commented on src/main/java/bowling/domain/Frame.java
> +        return message;
Try를 상속받은 객체를 여러 개 만들어서 사용하려고 하니 Optional<> 때문에 잘 되지 않아서 고민이네요..

2018-01-25 13:30 UTC, merged