Step1
code-squad/java-bowling pull request #53
Opened 2018-01-24 07:45 UTC by young891221

하다보니 계속 욕심이 생겨서 몇일간 붙잡고 있었는데 수요일을 넘어가면 안될거 같아서 PR보냅니다.ㅠㅠ
최대한 일급객체, Optional, Stream을 사용하려고 노력하였습니다.
점수상황에 따른 조건들 + 결과 포맷맞추기 때문에 코드가 복잡해 지는 느낌을 없애는게 힘드네요..
피드백 기다리겠습니다ㅎㅎ
감사합니다!

2018-01-24 09:32 UTC, javajigi requested changes
뭐라고 딱히 피드백하기는 힘든데요. 코드의 읽기가 쉽지 않네요. 많은 객체가 추가되고, 객체 간에 상호 의존관계를 가지다보니 그런 느낌이 드는 것 같아요. 피드백에도 남겼는데요. if/else를 제거하기 위해 다형성을 적용해 보는 것도 좋은 도전인 것 같아요.

2018-01-24 09:32 UTC, javajigi commented on src/main/java/bowling/domain/ScoreMachine.java
> +        return MISS.get();
if 문을 한 라인으로 구현하니 가독성이 더 떨어지는 것 같네요.

2018-01-24 09:32 UTC, javajigi commented on src/main/java/bowling/domain/frame/Frame.java
> +    int FINAL_FRAME = 10;
상수 값이면 static final로 구현해야하지 않나요? 
인터페이스에서 구현하면 상수 값으로 인식하나요?
제가 인터페이스에 이와 같이 구현해 보지 않아서 모르겠네요.

2018-01-24 09:32 UTC, javajigi commented on src/test/java/BowlingFinalTest.java
> +    private FinalFrame ThreeTimeNextFrame(int first, int second, int third) {
메소드 이름은 소문자로 시작

2018-01-24 09:32 UTC, javajigi commented on src/main/java/bowling/domain/frame/FinalFrame.java
> +public class FinalFrame implements Frame {
조건문이 너무 복잡하고 메소드도 많아 코드를 이해하는데 어려움이 있네요.
각 프레임의 상태를 담당하는 클래스를 추가하고 각 상태에 따라 다른 구현이 가능하도록 다형성을 적용해 구현해보면 어떨까요?
이건 10 프레임 뿐만 아니라 1 ~ 9 프레임도 동일한 구조로 구현할 수 있을 것 같은데요.

2018-01-24 09:32 UTC, javajigi commented on src/main/java/bowling/domain/frame/Frame.java
> +    Element getElement();
인터페이스 추가하고 구현 시도한 것은 👍

2018-01-24 09:32 UTC, javajigi commented on src/main/java/bowling/domain/frame/Frame.java
> +    String THIRD_SCORE = "third";
이와 같이 하드코딩하는 것이 썩 마음에 들지는 않네요.
맵이 아니라 ArrayList를 사용하면 0, 1, 2의 순서를 통해 알 수 있는데요.
굳이 Map을 쓰고, 키 값을 이와 같은 문자열로 구현해야 하나요?

2018-01-24 09:32 UTC, javajigi commented on src/main/java/bowling/domain/frame/element/Element.java
> +public abstract class Element {
이 객체의 역할과 객체의 이름이 잘 매칭이 되지 않는 것 같아요.
좀 더 나은 이름이 없을까요?

2018-01-24 10:38 UTC, ssosso commented on src/main/java/bowling/domain/frame/Frame.java
> +    int FINAL_FRAME = 10;
네 인터페이스에 변수를 선언하면 static final과 동일한 상수로 사용됩니다.

2018-01-24 10:40 UTC, young891221 commented on src/main/java/bowling/domain/frame/Frame.java
> +    int FINAL_FRAME = 10;
아, 인터페이스에 변수를 선언하면 static final로 선언한것과 동일하게 상수로 생성됩니다:)

2018-01-24 10:40 UTC, young891221 commented on src/main/java/bowling/domain/frame/Frame.java
> +    Element getElement();
감사합니다ㅎㅎ

2018-01-24 10:41 UTC, young891221 commented on src/test/java/BowlingFinalTest.java
> +    private FinalFrame ThreeTimeNextFrame(int first, int second, int third) {
헛 실수했네요...수정하겠습니다.

2018-01-24 11:01 UTC, young891221 commented on src/main/java/bowling/domain/ScoreMachine.java
> +        return MISS.get();
네 수정하겠습니다ㅠㅠ

2018-01-24 13:42 UTC, young891221 commented on src/main/java/bowling/domain/frame/element/Element.java
> +public abstract class Element {
EntireScore로 변경하였습니다.

2018-01-24 13:43 UTC, young891221 commented on src/main/java/bowling/domain/frame/Frame.java
> +    String THIRD_SCORE = "third";
음...리스트도 처음에 생각했는데요.
리스트는 무한데로 들어가고 어차피 3개만 들어간다면 Map이 더 명확하지 않을까 생각했는데...
고쳐보니 리스트가 더 편리한거 같네요. 감사합니다.

2018-01-24 13:44 UTC, young891221 commented on src/main/java/bowling/domain/frame/FinalFrame.java
> +public class FinalFrame implements Frame {
넵, 중간까지는 잘 가다가 마지막에 테스트 코드의 규칙만 짜맞추느라 코드가 엉망이 된거 같습니다ㅠㅠ
시간들여서 구조부터 명확히 잡고 다시 PR드리도록 하겠습니다. 피드백 감사합니다.

2018-01-28 11:17 UTC, young891221 commented
처음 설계가 잘못되서 코드를 리펙토링하게 되면 시간과 고통이 얼마나 드는지 몸소 체험해 볼 수 있는 리펙토링 시간이였습니다...ㅎㅎ
말씀하신데로 다형성과 중복 코드를 제거하도록 노력했습니다.
테스트 코드가 존재했기에 리펙토링이 가능했던거 같습니다.(테스트 코드의 중요성 실감..)
피드백 기다리겠습니다.
감사합니다!

2018-01-28 12:09 UTC, merged