Step2
code-squad/java-bowling pull request #55
Opened 2018-01-25 11:23 UTC by Gunju-Ko

Step1의 구현이 너무 복잡하고, Step2의 요구사항을 반영하기가 어려워서 전면 수정했습니다.
(잘 못 구현한 부분도 있었습니다..)

그래서 Pull Request의 단위도 엄청 크고, 보기도 힘드네요 ㅠㅠ
죄송합니다.ㅠㅠ

2018-01-25 12:23 UTC, javajigi requested changes
구조를 바꿨는데 더 깔끔하게 구현 잘 하셨네요. 다형성을 경험해 봤으면 해서 피드백 남겼어요. 한 단계 더 나은 경험을 해보면 좋겠어요.

2018-01-25 12:23 UTC, javajigi commented on src/test/java/domain/score/FinalScoreTest.java
> +        assertThat(score.toString()).isEqualTo("7|3|5");
테스트 메소드 하나에서 너무 많은 경우의 수를 테스트하고 있네요.
정말 필요한 경우에 대해서만 검증할 방법을 찾아보면 좋겠어요.

만약 이렇게 많은 경우의 수를 테스트해야 한다면 구현이 너무 복잡할 수도 있다는 생각이 듭니다. Pin 하나 추가했는데 너무 변경되는 것이 많다면 문제의 소지가 있어 보여요.

2018-01-25 12:23 UTC, javajigi commented on src/test/java/domain/score/ScoreTypeTest.java
> +        assertThat(ScoreType.valueOf(new Pin(5), new Pin(4))).isEqualTo(MISS);
한 가지 경우만 테스트해도 될 것 같아요.

2018-01-25 12:23 UTC, javajigi commented on src/test/java/domain/score/ScoreTypeTest.java
> +        assertThat(ScoreType.valueOf(new Pin(0), new Pin(10))).isEqualTo(SPARE);
한 가지 경우만 테스트해도 될 것 같아요.

2018-01-25 12:23 UTC, javajigi commented on src/test/java/domain/score/ScoreTypeTest.java
> +        assertThat(ScoreType.valueOf(new Pin(9))).isEqualTo(NONE);
한 가지 경우만 테스트해도 될 것 같아요.

2018-01-25 12:23 UTC, javajigi commented on src/main/java/domain/score/FinalScore.java
> +        throw new IllegalStateException();
메소드 하나에서 경우의 수가 너무 많네요.

힌트를 통해 전체 구조를 변경할 수 있을지 모르겠지만 "볼링 게임 점수판 2단계 - 힌트" 문서를 참고해 if/else를 제거해 보는 시도를 해보면 좋을 것 같아요. 이번 기회에 다형성을 통해 조건절을 줄이는 경험을 해보면 좋겠어요.

지금 단계에서 merge해도 충분한데요. 다음 경험을 위해 힌트를 통해 다시 한번 도전해 보는 것도 좋을 것 같아 제안해 봅니다.

2018-01-25 13:42 UTC, Gunju-Ko commented on src/test/java/domain/score/ScoreTypeTest.java
> +        assertThat(ScoreType.valueOf(new Pin(9))).isEqualTo(NONE);
네 너무 많긴하네요.. 쓸모없는 테스트는 전부 삭제하겠습니다

2018-01-25 13:44 UTC, Gunju-Ko commented on src/test/java/domain/score/FinalScoreTest.java
> +        assertThat(score.toString()).isEqualTo("7|3|5");
아 네 그냥 생각없이 모든 경우를 테스트하는 코드를 작성한거 같습니다..
필요한 부분만 남기고 다 지우겠습니다.

2018-01-25 13:45 UTC, Gunju-Ko commented on src/main/java/domain/score/FinalScore.java
> +        throw new IllegalStateException();
네 한번 더 고민해보겠습니다. 감사합니다.

2018-01-25 15:18 UTC, Gunju-Ko commented on src/test/java/domain/score/FinalScoreTest.java
> +        assertThat(score.toString()).isEqualTo("7|3|5");
네 지금 보니깐 너무 불필요한 체크를 많이하네요. 수정하겠습니다

2018-01-26 23:21 UTC, javajigi requested changes
State 객체와 자식들을 추가하면서 코드가 깔끔해 졌네요. 그런데 어떤 State인지를 판단하기 위해 instanceof를 많이 사용했네요. instanceof를 사용하는 부분의 로직을 State로 위임해 instanceof를 사용하지 않고도 구현이 가능하도록 리팩토링해보세요. 그렇게 구현해야 다형성의 참 맛을 느낄 수 있거든요.

2018-01-26 23:21 UTC, javajigi commented on src/main/java/domain/frame/NormalFrame.java
> +        return state instanceof Finish;
각 State별로 종료 상태인지를 알 수 있으니 State에 isFinsih()와 같은 메소드를 추가하면 어떨까요?
`rerturn state.isFinish()`와 같이 구현하면 instanceof을 통해 매번 체크할 일이 사라질 것 같은데요.

2018-01-27 01:57 UTC, Gunju-Ko commented on src/main/java/domain/frame/NormalFrame.java
> +        return state instanceof Finish;
제가 instanceOf를 사용했던게 이 점수의 상태가 MISS인지 STRIKE인지 SPARE인지 알아야하는데, 이러한 메소드를 모두 추가하면 (isMiss(), isStrike(), isSpare()) 코드가 되게 별로일거 같아서 그랬는데, instanceOf를 쓰는것도 별로 인거 같네요..
state에 getType이라는 메소드를 추가하고, 해당 메소드가 state의 타입을 반환하도록 구현하도록 하겠습니다. 그러면 훨씬 더 깔금해질거 같아요!!

2018-01-27 08:00 UTC, javajigi requested changes
이전과 동일한 피드백 하나 남겼어요. 이 피드백은 다형성 연습을 위해 반드시 구현해 봤으면 좋겠습니다.

2018-01-27 08:00 UTC, javajigi commented on src/main/java/domain/frame/NormalFrame.java
> +        return state.getType() != PinType.NOT_FINISH;
state에 isEnd() 메소드를 추가한 후 각 상태에서 따라 종료 여부를 결정하면 이와 같이 Type을 비교하는 부분이 사라질 수 있어요. 다시 한번 고려해 보면 좋겠어요.

즉, 1 ~9 프레임의 경우 Miss, Spare, Strike는 isEnd 값이 true이고, Ready, FirstBowl은 false가 되는 방식이겠죠. 우리가 다형성을 쓰는 이유는 이와 같이 type을 매번 체크하거나 instanceof를 사용하지 않기 위함입니다.

2018-02-08 16:40 UTC, javajigi approved these changes
정말 힘든 과정을 통해 코드가 많이 깔끔해 졌네요. 쉽지 않았을텐데 칭찬해 주고 싶네요.

2018-02-08 16:40 UTC, merged