Step1
code-squad/java-bowling pull request #57
Opened 2018-01-25 13:04 UTC by kimc1905

클래스를 분리했다가 다시합치는 작업을 몇번 반복했더니 늦었네요.
리뷰 부탁드립니다.

2018-01-25 13:17 UTC, javajigi requested changes
객체 추출 및 전체적인 구조가 정말 깔끔하네요. 제가 피드백할 부분이 거의 없네요. 그래도 의구심 나는 부분과 의견 몇 개 남겨 봤어요.

2018-01-25 13:17 UTC, javajigi commented on src/main/java/bowling/domain/BowlingGame.java
> +        return currentFrame instanceof LastFrame && currentFrame.isEnd();
Frame에 isEndGame() 메소드를 구현하고 위임하면 좀 더 깔끔하게 구현 가능할 것 같아요.

2018-01-25 13:17 UTC, javajigi commented on src/main/java/bowling/domain/BowlingGame.java
> +                .forEach(i -> frames.addFirst(new Frame(frames.getFirst())));
`frames.addFirst(new Frame(frames.getFirst()))` 뭔가 좀 어색한데요.
다른 방식으로 구현할 방법은 없을까요?

2018-01-25 13:17 UTC, javajigi commented on src/main/java/bowling/domain/DownPinCount.java
> +public class DownPinCount {
이 클래스 추가 👍

2018-01-25 13:17 UTC, javajigi commented on src/main/java/bowling/domain/DownPinCount.java
> +
이런 메소드 추가하면 어떨까요?

```
public boolean isStrike() {
    return count == 10;
}

public boolean isSpare(DownPinCount secondThrow) {
    return count + secondThrow.count == 10;
}
```

2018-01-26 01:49 UTC, kimc1905 commented on src/main/java/bowling/domain/DownPinCount.java
> +
좋은 지적 감사합니다. 
add에는 한 프레임에서 10개 이상의 핀이 쓰러지게끔 하는지 확인하는 의도가 있습니다.

의견 주신부분의 isSpare에서 아래와 같이 add를 사용하도록 변경하였습니다.
```java
public boolean isSpare(@Nonnull DownPinCount other) {
   return add(other).count == 10;
}
```

2018-01-26 01:52 UTC, kimc1905 commented
피드백 주신 내용은 반영 하였습니다. 
추가적으로 이번 구현에서 Optional을 적극적으로 썼는데 좀 과했던것 같네요.
커밋 메시지에도 남겼지만 파라미터에 사용되는 Optional은 제거 하였습니다.

2018-01-26 01:58 UTC, kimc1905 commented on src/main/java/bowling/domain/DownPinCount.java
> +
좋은 지적 감사합니다. 
add에는 한 프레임에서 10개 이상의 핀이 쓰러지게끔 하는지 확인하는 의도가 있습니다.

의견 주신부분의 isSpare에서 아래와 같이 add를 사용하도록 변경하였습니다.
```java
public boolean isSpare(@Nonnull DownPinCount other) {
   return add(other).count == 10;
}
```

2018-01-26 02:28 UTC, merged