Step2
code-squad/java-bowling pull request #58
Opened 2018-01-25 15:00 UTC by retrokarr

step2 진행해 보았습니다.
클래스를 좀 더 나눠보고 싶었는데 쉽지않네요.
여러 유저를 받아 게임을 진행해도 되도록 구현되었습니다.

2018-01-26 00:51 UTC, javajigi requested changes
구현 깔끔하게 잘 하셨네요. 특별히 피드백할 부분이 많지 않고 힌트를 참고해 다형성을 경험해 보면 좋을 것 같아요. step3 요구사항이 n명의 사용자를 구현하는 것이였는데 미리 구현하셨네요.

2018-01-26 00:51 UTC, javajigi commented on src/main/java/bowling/domain/Frame.java
> +public abstract class Frame {
이 클래스에 rollBowlingBall 메소드의 인자가 Pin인데요.
int로 받은 후에 이 메소드 내에서 Pin을 생성해 구현하는 것도 테스트 등의 코드를 좀 더 깔끔하게 구현할 수 있어 좋을 것 같아요. rollBowlingBall 메소드 이후부터 Pin을 사용하면 어차피 구현은 지금과 같으니까 문제 없을 것 같은데 어떨까요?

2018-01-26 00:51 UTC, javajigi commented on src/main/java/bowling/domain/Frame.java
>      protected Pin secondTry;
2단계 힌트를 참고해서 각 Pin의 상태를 객체로 분리하고 로직을 구현해 보면 어떨까요?
이와 같이 구현할 경우 기존과 어떻게 다른지 경험해 보면 좋을 것 같아요.

2018-01-26 15:42 UTC, retrokarr commented on src/main/java/bowling/domain/Frame.java
> +public abstract class Frame {
넵 Pin에서 예외처리를 다 해주기 때문에 그 편이 더 좋을것 같습니다. 감사합니다

2018-01-26 15:43 UTC, retrokarr commented on src/main/java/bowling/domain/Frame.java
>      protected Pin secondTry;
많은 공부가 됐습니다. 감사합니다 :)

2018-01-26 15:45 UTC, retrokarr commented
힌트와 코멘트를 참고하여 기존 코드에 적용해 봤습니다. 코드가 많이 깔끔해 졌네요 많은 공부가 됐습니다. 감사합니다 :)

2018-01-26 23:10 UTC, javajigi requested changes
힌트의 의도를 정확히 파악해서 잘 구현하셨네요. 이와 같이 상태가 변경되는 부분을 객체로 추상화해 구현하는 패턴을 State 디자인 패턴이라고 합니다. merge하려다 혹시 인터페이스를 잘 모르는 것이 아닌 생각해 피드백 하나 남겼어요.

2018-01-26 23:10 UTC, javajigi commented on src/main/java/bowling/domain/state/State.java
> +    public abstract Score addScore(Score score);
추상 메소드만 있는 경우 interface로 구현하면 더 깔끔합니다.

```
public interface State {
  State bowlBall(Pin fallenPin);
}
```

인터페이스는 기본이 public이기 때문에 접근 제어자를 추가할 필요도 없습니다.

2018-01-27 03:51 UTC, retrokarr commented on src/main/java/bowling/domain/state/State.java
> +    public abstract Score addScore(Score score);
넵 수정하겠습니다. 감사합니다.

2018-01-27 07:29 UTC, merged