Step1 done
code-squad/java-bowling pull request #65
Opened 2018-03-21 05:27 UTC by SANGCO

2018-03-21 09:09 UTC, javajigi requested changes
요구사항에 비해 좀 과도하게 설계한 느낌이 든다. 너무 추가 요구사항에 대한 집착이 있는 것은 아닌지. 훨씬 더 단순하게 구현할 수도 있을 것 같은데..

2018-03-21 09:09 UTC, javajigi commented on src/main/java/bowling/Frame.java
> +	public int getCurrentFrameNo() {
getCurrentFrame() 메소드 이용하면 되지 않을까?

2018-03-21 09:09 UTC, javajigi commented on src/main/java/bowling/Frame.java
> +	public State getCurrentFrameState() {
getCurrentFrame() 메소드 이용하면 되지 않을까?

2018-03-21 09:09 UTC, javajigi commented on src/main/java/bowling/Frame.java
> +		state = (State) new FirstBowl();
굳이 State으로 casting 할 필요 없음.

2018-03-21 09:09 UTC, javajigi commented on src/main/java/bowling/Frame.java
> +	public void setState(State state) {
setter 메소드가 있어야 하나? 없이 구현할 수는 없을까?

2018-03-21 09:09 UTC, javajigi commented on src/main/java/bowling/GameStart.java
> +		}
indent depth가 3인데 줄여보면 좋겠다.

2018-03-21 09:09 UTC, javajigi commented on src/main/java/bowling/LastFrame.java
> +		// State Last를 이용해서 점수 계산을 마무리 하자.
구현 끝난 것 맞나?
왜 아무일도 하지 않지?

2018-03-21 09:09 UTC, javajigi commented on src/main/java/bowling/Frame.java
> +	public abstract void InputBowl(Pins pins);
추상 메소드는 대문자로 시작해야 하나?

2018-03-21 09:09 UTC, javajigi commented on src/main/java/bowling/NomalFrame.java
> +		if (state instanceof Running) {
instanceof를 쓰지 않고 state.isFinish()와 같은 메소드 구현해 해결하면 어떨까?

2018-03-21 09:09 UTC, javajigi commented on src/main/java/bowling/Pins.java
> +	private final int MAX = 10;
상수는 static final
인스턴스 변수 앞에 위치하는 것이 convention

2018-03-21 09:09 UTC, javajigi commented on src/main/java/state/Nomal.java
> +public class Nomal extends State implements Finish {
Normal

2018-03-21 09:09 UTC, javajigi commented on src/main/java/state/Strike.java
> +	}
State의 상속 구조를 만들었는데 괜히 복잡도만 높아지고 제대로 활용하지 못하는 것 같다.
너무 기존에 했던 방식에 얽매여 있는 것은 아닌지?

2018-03-28 00:58 UTC, javajigi requested changes
구현 잘 했네. Frame이라는 부모 클래스를 추가했는데 이에 대한 피드백 좀 남겼다. 그리고 각 Frame의 상태를 인스턴스 변수로 가지면서 변경해 나가지 말고 메소드를 호출해 처리하도록 개선해봐라. 그러면 코드 복잡도가 많이 줄어든다. 인스턴스 변수의 수를 최소화한다.

2018-03-28 00:58 UTC, javajigi commented on .idea/uiDesigner.xml
> +</project>
.idea 디렉토리를 ignore 처리하면 좋겠다.
불필요한 코드가 너무 많이 추가되었다.

2018-03-28 00:58 UTC, javajigi commented on src/main/java/bowling/BowlingGame.java
> +			while (frame.isEndGame() == false) {
while(!frame.isEndGame()) 과 같이 구현 가능함.

2018-03-28 00:58 UTC, javajigi commented on src/main/java/bowling/Frame.java
> +	protected Pins secondRoll;
인스턴스 변수를 private으로 변경한 후 구현해 본다.

2018-03-28 00:58 UTC, javajigi commented on src/main/java/bowling/Frame.java
> +	protected boolean frameDone = false;
이 인스턴스 변수가 필요한가?
메소드 호출을 통해 해결할 수는 없나?

2018-03-28 00:58 UTC, javajigi commented on src/main/java/bowling/Frame.java
> +		return false;
return secondRoll == null;
위와 같이 한 줄로 구현 가능함.

2018-03-28 00:58 UTC, javajigi commented on src/main/java/bowling/FrameNo.java
> +	}
이 클래스 추가한 것 :+1:

2018-03-28 00:58 UTC, javajigi commented on src/main/java/bowling/FrameNo.java
> +		return new NormalFrame(new FrameNo(frameNo.getFrame() + 1));
이 객체가 Frame을 생성하는 것은 적합해 보이지 않음.
nextFrameNo를 생성하는 것은 합당해 보임.

2018-03-28 00:58 UTC, javajigi commented on src/main/java/bowling/FrameNo.java
> +	public Frame createNextFrame(FrameNo frameNo) {
public FrameNo createNextFrameNo() {
}

인스턴스 메소드이기 때문에 굳이 FrameNo를 인자로 전달할 필요가 없음.

2018-03-28 00:58 UTC, javajigi commented on src/main/java/bowling/LastFrame.java
> +	private boolean endGame;
인스턴스 변수로 구현하지 말고 isEndGame() 메소드를 호출할 때 판단하도록 구현하는 습관을 들인다.

2018-03-28 00:58 UTC, javajigi commented on src/main/java/bowling/LastFrame.java
> +		if (endGame) {
if (isEndGame())

2018-03-28 00:58 UTC, javajigi commented on src/main/java/bowling/LastFrame.java
> +		if (frameDone) {
if (isFrameDone())

2018-03-28 00:58 UTC, javajigi commented on src/main/java/bowling/LastFrame.java
> +		return endGame;
이 메소드는 return isFrameDone(); 조건을 체크하면 됨.

2018-03-28 00:58 UTC, javajigi commented on src/test/java/bowling/NomalFrameTest.java
> +		assertThat(frame.getCurrentFrame().toString(), is("Frame [frameNo=6]"));
테스트 코드 :+1:

2018-03-28 00:58 UTC, javajigi commented on src/main/java/bowling/Frame.java
> +	public abstract void roll(Pins pinsDown);
Pins로 받지 않고 int로 받는 것도 방법이다.
int로 받은 후 roll() 메소드 내에서 Pins로 변환

2018-03-28 02:11 UTC, SANGCO commented on src/main/java/bowling/FrameNo.java
> +		return new NormalFrame(new FrameNo(frameNo.getFrame() + 1));
FrameNo는 몇번째 프레임인지에 대한 정보를 가지고 있으니
그 정보와 관련된 기능만 구현하게 하는게 맞겠군요.

2018-03-28 02:12 UTC, SANGCO commented on src/main/java/bowling/Frame.java
> +		return false;
그러네요. == 연산자의 결과가 true or false 이니

2018-03-28 02:13 UTC, SANGCO commented on src/main/java/bowling/Frame.java
> +	protected boolean frameDone = false;
객체지향에 대해 생각하다가 또 예날 버릇이 나와버렸네요.
메소드 호출로  해결을 하고 앞으로도 인스턴스 변수를 최대한 줄이도록
버릇을 드려야겠네요~

2018-03-28 02:15 UTC, SANGCO commented on .idea/uiDesigner.xml
> +</project>
생각없이 다 올렸었는데 
어떤건 올릴 필요가 없는지 생각을 해봐야겠네요.

2018-03-28 02:15 UTC, SANGCO commented on src/main/java/bowling/BowlingGame.java
> +			while (frame.isEndGame() == false) {
그러네요. 머리가 굳었나 이런게 안보이네요ㅋ

2018-03-28 02:16 UTC, SANGCO commented on src/main/java/bowling/Frame.java
> +	protected Pins secondRoll;
이거 어제 리버웨이한테 피드백 하실 때 뜨끔했었습니다ㅋ
고민해 봐야겠네요.

2018-03-28 02:16 UTC, SANGCO commented on src/main/java/bowling/FrameNo.java
> +	}
앞으로도 매개변수로 넘어가는 값들에 대해서 객체로 추상화 할 수 없는지
객체로 뽑으면 어떤일을 시킬지 고민을 해보겠습니다~

2018-03-28 02:18 UTC, SANGCO commented on src/main/java/bowling/FrameNo.java
> +	public Frame createNextFrame(FrameNo frameNo) {
헉 그러네요ㅜㅜ

2018-03-28 02:24 UTC, SANGCO commented on src/main/java/bowling/Frame.java
> +	public abstract void roll(Pins pinsDown);
생각해보니 실행의 흐름을 제어하는 쪽보다 여기서 하는게 맞는거 같네요~

2018-03-29 00:54 UTC, merged