step1
code-squad/java-bowling pull request #68
Opened 2018-04-09 05:22 UTC by durin93

step1구현해보았습니다.

2018-04-09 05:46 UTC, javajigi requested changes
코드 구현이 좀 복잡해지는 느낌이 든다. 지금 단계에서 좀 더 단순화하지 않으면 step2 구현에 어려움이 있을 것 같다. 좀 더 개선해 보면 좋겠다.

2018-04-09 05:46 UTC, javajigi commented on src/main/java/bowling/domain/Game.java
> +	String name;
인스턴스 변수는 특별한 이유는 없는 한 private으로 구현한다.
객체 외부에서 상태 값을 임의로 변경할 수 있도록 하는 것은 캡슐화 위반이다.

2018-04-09 05:46 UTC, javajigi commented on src/main/java/bowling/domain/Frame.java
> +		return firstDownPin == 10;
값을 하드코딩하지 마라.
상수(static final)를 만들고 이름을 부여해 이 변수의 역할이 무엇인지 의도를 드러내라.

2018-04-09 05:46 UTC, javajigi commented on src/main/java/bowling/domain/Frame.java
> +		return firstDownPin == (10 - inputThrowScore);
값을 하드코딩하지 마라.
상수(static final)를 만들고 이름을 부여해 이 변수의 역할이 무엇인지 의도를 드러내라.

2018-04-09 05:46 UTC, javajigi commented on src/main/java/bowling/domain/Game.java
> +	public Frame getFrame(int frameNum) {
`return frames.get(frameNum)` 이렇게 구현하면 안되나?

2018-04-09 05:46 UTC, javajigi commented on src/main/java/bowling/domain/Game.java
> +	public void setFrame(int frameNum, Frame frame) {
setter 메소드를 사용하지 않고 구현해 본다.

2018-04-09 05:46 UTC, javajigi commented on src/test/java/NormalFrameTest.java
> +
로직 구현이 너무 복잡함.
객체 지향의 맛을 제대로 활용하지 못하고 있는 느낌이 든다. 전체적인 객체 설계에 대해 다시 한번 고민해 보면 좋겠다.

2018-04-09 05:46 UTC, javajigi commented on src/main/java/bowling/domain/Game.java
> +	public Boolean addNormalFrame(int inputThrowScore, int frameNum, int throwTime) {
private이어도 되는 것 아닌가?

2018-04-09 05:46 UTC, javajigi commented on src/main/java/bowling/domain/Frame.java
> +	public Frame(int num, int firstDownPin, int secondDownPin) {
1frame 첫번째 투구의 경우 두 번째 값이 없을 수도 있는데 이와 같이 두번째 값까지 전달하도록 구현할 수 있나?

2018-04-09 05:46 UTC, javajigi commented on src/main/java/bowling/domain/LastFrame.java
> +	public static LastFrame of(int num, Frame frame, int thridDownPin) {
오타

2018-04-10 05:01 UTC, durin93 commented
피드백을 반영해서 전체적으로 수정해보았습니다.
기존에는 출력을 하면서 동시에 프레임객체를 생성을 했었는데, 이러다보니 set을 사용하게 되었고, 
그래서 이번에는 출력 시에 점수를 점수라는 객체에 담아 출력을 한 뒤, 해당 객체를 이용해 프레임 객체를 생성하는 방식으로 수정 하였습니다,

2018-04-10 05:30 UTC, javajigi requested changes
Score를 추가하면서 코드가 이전보다는 훨씬 더 깔끔해진 느낌이다. 👍 생각해볼꺼리 포함해 작은 피드백 몇 개 남겨본다.

2018-04-10 05:30 UTC, javajigi commented on src/main/java/bowling/domain/Frame.java
> +	protected int secondDownPin;
부모의 인스턴스 변수를 protected가 아니라 private으로 구현하라는 한다면 어떻게 하는 것이 좋을까?
반드시 protected을 사용해 구현해야 하나? private으로 구현할 수 없나?

2018-04-10 05:30 UTC, javajigi commented on src/main/java/bowling/domain/Frame.java
> +		if (firstDownPin == 10) {
값을 하드코딩하지 마라.
상수(static final)를 만들고 이름을 부여해 이 변수의 역할이 무엇인지 의도를 드러내라.

10이라는 값이 많은 곳에서 사용되고 있다.

2018-04-10 05:30 UTC, javajigi commented on src/main/java/bowling/domain/Frame.java
부모 클래스에서 추상 메소드로 구현할 부분은 없는 건가?

2018-04-10 05:42 UTC, durin93 commented on src/main/java/bowling/domain/Frame.java
> +	protected int secondDownPin;
아 이부분 제가 private으로 구현하기 위해 메서드를 부모클래스로 옮겨서 구현했었는데
protected를 private으로 수정하지 않았었네요. 수정하겠습니다.

2018-04-10 07:48 UTC, durin93 commented
피드백반영하여 수정해보았습니다.
부모클래스에서 추상메소드로 구현할 부분은 생각해보다가
현재의 출력방식에서는 당장은 필요없었지만, 나중에 프레임객체를 이용해 전체를 출력해야될 경우에는
일반프레임과 마지막프레임의 출력부가 달라지기때문에
그부분을 추상메서드로 구현하고 자식클래스에서 구현해보았습니다.
그리고 최대한 get을 안쓰기 위해 부모클래스에 메서드를 만들어서 활용하였습니다.

2018-04-10 09:34 UTC, merged