Step2.0
code-squad/java-bowling pull request #78
Opened 2018-04-17 01:14 UTC by durin93

step2구현해보았습니다.

2018-04-17 01:30 UTC, javajigi requested changes
볼링 로직을 객체로 추상화가 잘 되지 않다보니 많은 곳에서 if문이 남발하고 있다. 또한 객체의 상태 변경을 외부에서 처리하고 있는데 상태 데이터를 가지는 객체 자신의 자신의 상태 변경을 할 수 있도록 한다. 도전해보고 힘들면 힌트도 참고해 구현해 보면 좋겠다.

2018-04-17 01:30 UTC, javajigi commented on src/main/java/bowling/Main.java
> +		return pin;
이 메소드에서 값을 입력받는 로직을 제외한 나머지 로직을 game에서 처리하도록 할 수 없을까?
지금과 같이 외부에서 로직을 처리해 game의 상태를 업데이트하는 방식말고 game 인스턴스가 상태를 업데이트하도록 접근해 본다.

2018-04-17 01:30 UTC, javajigi commented on src/main/java/bowling/Main.java
> +		if (frameNum != Print.LAST_FRAME && pin.isStrike()) {
Print.LAST_FRAME 상수 값이 Print에 있는 것이 적합한 위치가 않은 것 같은 느낌이 든다.

2018-04-17 01:30 UTC, javajigi commented on src/main/java/bowling/domain/Pin.java
> +			}
indent 1로 줄여본다.

2018-04-17 01:30 UTC, javajigi commented on src/test/java/NormalFrameTest.java
>  	}
점수 계산을 위한 테스트 케이스 수가 훨씬 많을 것 같은데..
너무 제한적으로 테스트한 것 아닌가?
점수 계산에 대한 테스트케이스도 추가하면 좋겠다.

2018-04-17 01:30 UTC, javajigi commented on src/main/java/bowling/domain/Pin.java
> +	}
if 문이 너무 많은 곳에서 남발하고 있다.
객체 지향의 다형성을 활용해 if문 제거하거나 최소한으로 구현할 것을 시도해 본다.

2018-04-17 01:30 UTC, javajigi commented on src/main/java/bowling/domain/Score.java
>  }
현재 객체 대부분의 메소드가 public으로 오픈되어 있다. 정말 대부분의 메소드가 public이어야하는지 검토해 본다.

2018-04-17 01:30 UTC, javajigi commented on src/main/java/bowling/domain/Game.java
> +	public void updateScore(int inputScore, Pin pin, int frameNum) {
상태를 인스턴스 외부에서 결정해 수정하는 방식이 아니라 상태 데이터를 가지고 있는 Game이 주도하도록 한다.
현재 모든 Frame 데이터는 Game이 가지고 있고, 각 Frame의 상태 데이터는 Frame이 가지고 있다.
자신의 상태 변경을 인스턴스 자신이 주도록 한다.

2018-04-18 07:52 UTC, javajigi requested changes
지난 번 코드를 개선하느라 고생했다.

새로운 객체를 추가해 추상화를 하지 않으면 현재의 복잡도를 줄이기는 힘들어 보인다. 강의 문서의 힌트를 참고하거나 내가 구현한 https://github.com/code-squad/java-bowling/tree/javajigi 코드를 참고해 힌트를 얻어 개선해 보면 좋겠다.

객체 지향의 맛을 느껴봤으면 하는 바람으로 피드백 남겨본다.

2018-04-18 07:52 UTC, javajigi commented on src/main/java/bowling/domain/Game.java
> +		Print.printFrame(oneBall, name, frameNum, this);
도메인 로직에서 View에 접근하고 있다.
View -> Domain을 허용하되, Domain -> View를 허용하지 않는 구조로 구현한다.

2018-04-18 07:52 UTC, javajigi commented on src/main/java/bowling/domain/Game.java
> +		updateScore(inputScore, oneBall, frameNum);
Score를 계산하는 부분이 객체의 상태 단위가 아닌 단순히 메소드 인자의 전달을 통해 구현되고 있다.
이렇게 구현하다보니 메소드 인자의 수도 많아지고 복잡도도 높아지고 있다.

메소드의 안자 수를 2개까지만 허용하도록 노력해 봐라. 물론 정말 힘들 때는 3개까지 허용하겠지만 지금 너무 많은 메소드에 인자의 수가 많다.

2018-04-18 09:02 UTC, durin93 commented
지난번 피드백이후 로직을 Game객체 내부에서 돌아가게 하기위해 Game객체에 임시핀역할을 하는 Pin형 변수 oneBall을 추가했고 그걸 이용해서 Pin클래스의 메서드를 사용할수있게 로직을 돌리는 방식으로 구현해서 파라미터가 없어도 됬었는데 그 부분을 깜빡하고 메서드마다 pin파라미터를 하나씩 다 넣어놨었습니다.  그래서 그부분을 다 제거하고 View단도 꺼내어 파라미터를 많이 줄여보았습니다.

2018-04-19 03:07 UTC, merged