Step3
code-squad/java-bowling pull request #81
Opened 2018-04-18 04:28 UTC by imjinbro

# 구현한 것
1. 마지막 프레임 : 스트라이크 후 보너스 투구할 때 첫 점수 10점일 때와 아닐 때 분기
2. 프레임 연결 구조로 합산 점수 구하기
3. 점수판 출력 기능 : 1 ~ N명 플레이어 돌아가면서 플레이 -> 점수판 출력

2018-04-18 06:50 UTC, javajigi requested changes
전체적으로 구현은 깔끔하게 잘 했다. 👍 
그런데 데이터를 2중으로 관리하고, 끊임없이 객체의 상태를 확인하면서 로직을 처리하다보니 복잡도가 높아지는 경향이 있다. 상태 데이터를 하나만 관리하면서 로직을 처리할 수 없을지 고민해 보면 좋겠다.

2018-04-18 06:50 UTC, javajigi commented on src/main/java/domain/frame/BonusPins.java
> +public class BonusPins {
이 객체도 FrameStatus와 같은 형태로 처리할 수 없나?
아니면 10frame의 모든 상태 변화를 FrameStatus와 같이 10frame만의 status 처리를 한다면..

2018-04-18 06:50 UTC, javajigi commented on src/main/java/domain/frame/Frame.java
> +    final int frameNum;
이 인스턴스 변수가 private이 아닌 이유는?

2018-04-18 06:50 UTC, javajigi commented on src/main/java/domain/frame/Frames.java
> +        frames.forEach(frame -> frame.refreshPinNum(currentFrame));
투구한 pin의 수를 현재 Frame에 추가하는 것으로 끝낼 수 없을까?
전체 frames에 for문을 돌면서 refresh를 하는 이유는?
그 이유는 상태를 이중으로 관리하고 있기 때문에 sync를 맞추기 위함으로 판단되는데 이와 같이 이중으로 관리하는 데이터를 제거하고 구현해 본다.

2018-04-18 06:50 UTC, javajigi commented on src/main/java/domain/frame/LastFrame.java
> +        bonusPins.saveBonusPin(num);
score에도 투구한 값을 넣으면서 bonusPins에도 값을 넣어야 되나?
데이터를 이중으로 관리하는 것이 아닌가?

2018-04-18 06:50 UTC, javajigi commented on src/main/java/domain/frame/LastFrame.java
> +        recordPin(score, num);
score를 roll하면서 바로 increaseLeftCount()가 되도록 구현할 수는 없을까?

2018-04-20 01:19 UTC, imjinbro commented
# 수정한 것
* status와 pins 관계 다시 설정 : 이전에는 pins가 status를 결정해서 pins가 더 크다고 생각했었는데 결정적인 역할은 힌트를 보고나니 status가 하는게 맞더라구요 거꾸로 관계설정을 해놓다보니 pins의 개수가 각 상태마다 안맞음에도 억지로 맞추려고 로직이 더 복잡해졌음을 느꼈습니다.
  
* 라스트 프레임을 위한 상태 : 무조건 공통적인 status만 만들어야한다고 생각해서 strike, spare까지만 만들어놨었는데 이렇게도 할 수 있구나 라는 것을 피드백 통해서 알게되었습니다. 갇혀있던 사고를 깰 수 있었습니다.
  
* 점수 합산하기 :  이전 코드에서는 baseScore를 주고 합산하는 방식으로 했었는데 결과 출력할 때만 Result에서 꺼내와서 더해버리는 방식으로 바꿨습니다. 합산 시점을 바꿨더니 -1(계산할 수 없는 상태)을 쉽게 구별할 수 있게 되었습니다.
  
* 뷰와 도매인 로직이 분리가 되어있으니 도매인 로직만 수정해도 뷰는 아무런 상관없이 잘 돌아갔습니다. 또 한번 중요성을 느낍니다.

2018-04-20 02:26 UTC, javajigi requested changes
구현 잘 했다. 👍
네가 다른 친구들에 비해 여유가 있어 한번 더 도전해 보면 좋겠다는 마음이 들어 피드백 남겨봤다.

2018-04-20 02:26 UTC, javajigi commented on src/main/java/domain/frame/Frame.java
> +    public Score addBonusScore(Score beforeFrameScore) {
이 메소드는 10 frame에서만 필요한 것 아닌가?
만약 그렇다면 이 객체에 있는 것이 맞지 않을 것 같다.

2018-04-20 02:26 UTC, javajigi commented on src/main/java/domain/frame/status/BonusStrike.java
> +}
Bonus 관련된 상태 객체가 많이 추가되었네요.
내가 아침에 공유했는데 내가 1 ~ 9 프레임까지의 status를 활용해 어떻게 해결했는지 한번 리뷰해 보면 좋겠다.

2018-04-20 02:26 UTC, javajigi commented on src/main/java/domain/frame/Frame.java
> +        status = status.roll(this, new Pin(num));
status에 this(즉, Frame)가 전달되어야 하나?
this 전달하지 않고 구현할 수는 없을까?

2018-04-20 02:32 UTC, imjinbro commented on src/main/java/domain/frame/Frame.java
> +        status = status.roll(this, new Pin(num));
isFinish 구현해두고 써먹지않고 있었네요...;;;

2018-04-21 08:34 UTC, imjinbro commented
포비 코드 리뷰 그리고 수정을 하면서 느낀점은 특정 부분 문제를 해결하기위해서 새로운 것을 만들어내려고 하지말고 그 조건 하에서 문제를 해결할 수 있도록 구조적으로 접근해봐라는 점을 느낄 수 있었습니다. 큰 부분부터 생각을 더해보고 개발을 해야겠다는 생각이 많이 들었던 코드 리뷰였습니다......... 이런 경험을 할 수 있어서 굉장히 좋네요!(다음엔 실수 꼭 하지않게 잘 적어둬야겠습니다)

2018-04-23 00:57 UTC, merged