볼링 1단계 코드리뷰 부탁드립니다.
code-squad/java-bowling pull request #85
Opened 2018-04-19 18:00 UTC by serverwizard

교수님~ 코드 리뷰 부탁드릴게요~

2018-04-19 23:51 UTC, javajigi requested changes
볼링의 경우 상당히 복잡한 로직을 구현하는데 테스트 코드가 없는 것이 아쉽네요.
아마도 다음 step인 점수를 계산하는 경우 테스트가 없으면 특히 10 프레임 로직 구현할 때 어려움이 있을 것 같네요.

피드백 남겼어요. 구현은 깔끔하게 잘 했네요. 💯

2018-04-19 23:51 UTC, javajigi commented on src/main/java/domain/Frame.java
> +    public boolean isEndFrame() {
이 로직이 1~9와 10 프레임 구현이 다르지 않나요?
다르다면 추상 메소드가 맞지 않을까요?

2018-04-19 23:51 UTC, javajigi commented on src/main/java/domain/Frame.java
> +    public void setSecondFallingPinNum(int fallingPinNum) {
private이어도 되지 않나?

2018-04-19 23:51 UTC, javajigi commented on src/main/java/domain/Frame.java
> +    public void setFallingPinNum(int fallingPinNum) {
public -> protected이어도 되지 않나?

2018-04-19 23:51 UTC, javajigi commented on src/main/java/domain/Frame.java
> +        return getFirstRoll() + getSecondRoll();
상태를 가지는 객체의 데이터를 꺼내려(get)하지 말고 객체에 메시지를 보내라는 원칙에 따라 구현한다.

return firstRoll.totalPins(secondRoll);

이와 같이 구현하도록 사고할 수 있도록 연습한다.

2018-04-19 23:51 UTC, javajigi commented on src/main/java/domain/Frame.java
> +    public abstract int getCurrentFrameNo();
이 메소드가 굳이 추상 메소드여야 하나?

2018-04-20 15:33 UTC, serverwizard commented on src/main/java/domain/Frame.java
> +    public abstract int getCurrentFrameNo();
양쪽(NormalFrame, LastFrame)에서 똑같은 로직을가지고 사용하기때문에 추상 메소드가 아닌게 좋을것 같습니다.

2018-04-20 15:34 UTC, serverwizard commented on src/main/java/domain/Frame.java
> +        return getFirstRoll() + getSecondRoll();
습관이라는게 의식하지 않는 순간 또 스윽 나오는 것 같네요 ㅠ

2018-04-20 15:35 UTC, serverwizard commented on src/main/java/domain/Frame.java
> +    public void setSecondFallingPinNum(int fallingPinNum) {
내부에서만 사용하기때문에 private을 사용하는게 좋은 것 같습니다.

2018-04-20 16:23 UTC, serverwizard commented on src/main/java/domain/Frame.java
> +    public boolean isEndFrame() {
네. 다르기 때문에 추상메소드가 맞는것 같습니다.

2018-04-20 22:58 UTC, merged